# installation of alpinelinux-dockerhost

- hosts: all
  gather_facts: yes
  tasks:

  # User-Managment
  - file: path=/etc/ssh/dockeradmin state=directory owner=dockeradmin group=dockeradmin mode=0755
  - copy: src=files/dockeradmin.pub dest=/etc/ssh/dockeradmin/authorized_keys owner=dockeradmin group=dockeradmin mode=0644
  - lineinfile: dest=/etc/ssh/sshd_config line="AuthorizedKeysFile    /etc/ssh/%u/authorized_keys"
  - lineinfile: "dest=/etc/sudoers line='dockeradmin ALL=(ALL) NOPASSWD: ALL'"
  - user: name=dockeradmin shell=/bin/bash groups=adm,cdrom,sudo,dip,plugdev,lpadmin,sambashare password=!
  - service: name=ssh state=restarted
  
